services:
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: links_list
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
      - ./db/logs:/var/log
